version: '3'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    ports:
      - '55432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
#    volumes:
#      - ./events-pipeline-ui-core/src/main/resources/database/db-initial.sql:/docker-entrypoint-initdb.d/db-init.sql